### ISSUE TITLE
Not enough penises

### ISSUE THREAD

**Issue by mzieg** [jordiprats/python-penisipsum#1]

**Comment by jordiprats** [comment]
Do you mean it's not large enough?

You can change the number of words using the words option:

```
penisipsum.sentence(words=15, base_words="Penis ipsum", capitalize=True, add_period=True)
```

And the number of sentences optionally combining it with the number of words per sentence:

```
penisipsum.paragraph(sentences=5, max_words_per_sentence=15, min_words_per_sentence=3)
```
